### ISSUE TITLE
Question / Possible Bug | Icons having abnormal sharp corners

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign-Webfont#1]
I noticed something looked funny when loading the html file. I am using Chrome and W8.1.

![material design icons](https://cloud.githubusercontent.com/assets/5341898/5868980/a7a6ab26-a266-11e4-9c9d-c4b653a2bc33.png)

**Comment by Templarian** [comment]
Browser and version? This was fixed in v0.7.33-alpha (current version) last Saturday. There was an issue in one of the font builds, but was reverted after a few days of being released.

**Comment by danielhickman** [comment]
I just downloaded it a few minutes ago and my browser is Chrome 39.0.2171.99 dev-m

**Comment by Templarian** [comment]
![image](https://cloud.githubusercontent.com/assets/338885/5869280/2be902a2-a27c-11e4-9432-51a5c048127d.png)

39.0.2171.99 m Also. I just tested it in IE11 also. Same results. You didn't by chance install a legacy version into your operating system did you?

**Comment by Templarian** [comment]
Do you have all 733 icons in the font?

**Comment by danielhickman** [comment]
Yes

**Comment by Templarian** [comment]
I have no idea to be honest. Windows / Linux Distro / OSX?

I've tested in IE11 / Chrome / FF. All updated. It really looks like you have the legacy version that was broken the other week. Can you please try creating a new folder and do `bower install mdi` and let me know if you still see it?

**Comment by Templarian** [comment]
I'm close this in a bit if I don't hear a reply. I pulled it to my machine at work and it looked fine.

**Comment by danielhickman** [comment]
Yeah I don't know what went wrong. I may have done something wrong.

**Comment by Templarian** [comment]
Is it working now after deleting and doing a fresh `bower install mdi`?

**Comment by danielhickman** [comment]
I'm actually not sure how to do that. :/

**Comment by Templarian** [comment]
Oh crap. I forgot to push the v0.7.33-alpha tag in git to the master branch. I'll fix that in a bit, for now just use the link below.

https://github.com/Templarian/MaterialDesign-Webfont/archive/v0.7.33-alpha.zip

**Comment by Templarian** [comment]
Fixed, the master branch now has the latest from the `v0.7.33-alpha` tag.

I really need to stop doing commits at 2am. When I automate this I will configure it to always create the tag and verify everything was synced.

Thanks a bunch for bringing this to my attention, I never would have noticed until the next webfont update that I do on Saturdays.
