### ISSUE TITLE
Feature Request: Unlink / Break Link

### ISSUE THREAD

**Issue by muffinjello** [Templarian/MaterialDesign-Webfont#11]
Hello,

I'm using the icons for a text editor right now, and it would be lovely if there was an 'unlink' icon - something along the lines of the link-variant with a slash going through it?

That would be awesome, thanks!

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign/issues

Sorry can you resubmit that above and I'll get it added right away for the hassle. This repo is only for webfont related issues. :smile:
