### ISSUE TITLE
"mdi-voice" missing from css

### ISSUE THREAD

**Issue by nyeargh** [Templarian/MaterialDesign-Webfont#14]
On the homepage it says that there's an icon named `voice` but when using the style `mdi mdi-voice` it doesn't appear and when looking through the css it doesn't even exist.

**Comment by Templarian** [comment]
https://materialdesignicons.com/history Looks like it isn't in the latest release. Will have to wait until the next release (I'm working on a pretty sizable update to the webfont generation scripts so it will be a few more weeks until I have this out).
