### ISSUE TITLE
border-color icon alignement problem

### ISSUE THREAD

**Issue by SBRK** [Templarian/MaterialDesign-Webfont#16]
The border-color icon is not centered, which is problematic when using it with other icons, it is not aligned.
![border-color-align](https://cloud.githubusercontent.com/assets/119354/13354509/bb64b4d0-dc9b-11e5-95d9-b909052111ba.png)

I see the problem on the [png versions too](https://materialdesignicons.com/api/download/icon/png/CCD99C36-5D88-4696-8193-56F11C4B20A7)

**Comment by Templarian** [comment]
You need to stack the color-helper icon. If you just want a pencil use the pencil.

[![color-helper](https://materialdesignicons.com/icon/color-helper)](https://materialdesignicons.com/icon/color-helper)
