### ISSUE TITLE
Upgrading to PyScss v1.3.5 causes icons to use wrong 'content'

### ISSUE THREAD

**Issue by hurgleburgler** [Templarian/MaterialDesign-Webfont#19]
Using this webfont with the latest PyScss v1.3.5 (released today), causes breakage.  Honestly not sure if the breakage is on the side of PyScss or this package, any direction would be greatly appreciated.

Before the upgrade: https://i.imgur.com/0D0x5Bs.png
After the upgrade: https://i.imgur.com/ZDvWlai.png

**Comment by Templarian** [comment]
Can you retest this @hurgleburgler? The latest `v1.7.12` contained a lot of changes, one of them may have fixed this.
