### ISSUE TITLE
materialdesignicons.css path in bower main section

### ISSUE THREAD

**Issue by priithansen** [Templarian/MaterialDesign-Webfont#2]
I think "materialdesignicons.css" should be "css/materialdesignicons.css" in .bower.json? I see the css has moved in release 0.9* could it be that this was forgotten?

**Comment by Templarian** [comment]
That needs to be deleted out. The css/* handles it.

I just ran bower and it seems to ignore it. I'll fix it in the next release.

**Comment by priithansen** [comment]
Jeah sorry about that I'm using lumx with https://github.com/Swiip/generator-gulp-angular generator and mistakenly thought this fixed font paths generation for me but turned out to be something else.

**Comment by Templarian** [comment]
Either way, I forgot to delete that line when the folder structure got changed to match other popular webfont packages.

You are not seeing any issues with the line in there are you? If so I'll generate a new version. It appears to be in the previous version that was out for 2 weeks and no one said anything, so I assume it's fine till next week.

**Comment by priithansen** [comment]
I don't think this made much of a difference in my case because like you said css/* covered all the bases anyway.

What actually caused a problem for me is that swiip generator distribution folder structure is like this:
    
    styles/
      ~compiled.css
      fonts/
        ~font.woff  

Since this package has styles and fonts folder on same level the font path in css will be ../fonts and that does not work. But at the same time package like https://github.com/choffmeister/roboto-fontface-bower has css files in root with just fonts in separate sub folder and that works as expected.

For now as a quick patch I just have two copies of the fonts folder in dist. Not sure if there is any better clever way to sidestep that problem.

**Comment by Templarian** [comment]
My advice would be to not compile the bower or npm folders. Those always come pre-compiled.

I include the SASS so you can optionally add the imports into your own SASS file though (less is still being worked on).

**Comment by priithansen** [comment]
I think the generator just goes through all bower_components and combines css files into one nice vendor.css. Probably would be somehow possible to override scss variable if generated from scss sources but for now simpler pragmatic solution is to use just copy fonts and move on :) Thanks for the great package

**Comment by deel77** [comment]
I have the same problem with inproper materialdesignicons.css path, but for me css/* doesn't add any links to included css files, so I have to change path manually. Using yeoman.io generated grunt build.

**Comment by Templarian** [comment]
I'm doing an update that will remove this tonight. Turns out that some 3rd party tools completely stop pulling files if they run into a file that cannot be found.

Sorry about that. `v1.0.0-beta` will hopefully go out tonight. I'll close this issue when it checked in and tested.

**Comment by Templarian** [comment]
`v1.0.8-beta` is released.
