### ISSUE TITLE
Howto build fonts?

### ISSUE THREAD

**Issue by pjfsilva** [Templarian/MaterialDesign-Webfont#30]
Right now the main website (materialdesignicons.com) has a few icons described that are not yet in this webfont (mdi-circle, etc) which is a bit annoying. 

Can you add instructions how to build the font files from the raw svg files?

**Comment by Templarian** [comment]
We're working on this for the new site. There will also be a nightly build to the CDN that will always contain the latest. This repo will only contain the releases.

Basically `grunt-webfont` can build the entire webfont. It's kind of picky, so it needs the https://materialdesignicons.com/design files, unfortunately for now these are only updated with each release.

The new site pulls all it's content from markdown files, one will be the guide below.
https://github.com/Templarian/MaterialDesign-Site/blob/master/src/content/guide-webfont.md

There is an open issue for this also that can be tracked below:
https://github.com/Templarian/MaterialDesign-Site/issues/17

Closing this issue out, please use the issue above to track process and provide followup feedback. Thanks!
