### ISSUE TITLE
mdi-flip-horizontal and mdi-rotate don't seem to be working

### ISSUE THREAD

**Issue by pjfsilva** [Templarian/MaterialDesign-Webfont#31]
I  think all code in _extras.scss should be applied to :before but it wasn't updated to it when the icons were changed to be used on :before.

At least I tried the flip and rotate thing and they don't seem to work unless applied to :before.

**Comment by Templarian** [comment]
Sounds like a bug, good thing we're just about to release `v1.9.xx` and can fix it right before.

Thanks!

**Comment by Templarian** [comment]
This has been resolved in the latest `v1.9.32` (aka `v1.9.33` release).

**Comment by Templarian** [comment]
Huge note, since they were never working I renamed them to `mdi-flip-h` and `mdi-flip-v`.

You can preview them at the bottom of https://cdn.materialdesignicons.com/1.9.32/
