### ISSUE TITLE
Add animated icons (spinning)

### ISSUE THREAD

**Issue by pjfsilva** [Templarian/MaterialDesign-Webfont#32]
To match font-awesome features I would add the possibility to spin icons to _extras.scss file. Something like the following

```
.mdi-spin:before {
  -webkit-animation: mdi-spin 2s infinite linear;
  animation: mdi-spin 2s infinite linear;
}

@-webkit-keyframes mdi-spin {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(359deg);
    transform: rotate(359deg);
  }
}
@keyframes mdi-spin {
  0% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(359deg);
    transform: rotate(359deg);
  }
}
```

**Comment by Templarian** [comment]
It's already in `v1.9.xx` releasing this weekend. 😄

**Comment by pjfsilva** [comment]
oh, didn't see that in the repo. What's the repo where that is updated?

**Comment by Templarian** [comment]
This repo is just a distribution, we don't have a repo for the webfont build unfortunately. We manage all issues through the MaterialDesign repo also. Generally I just close issues over here and track them there.
