### ISSUE TITLE
author, version & tags attributes are missing from meta.json

### ISSUE THREAD

**Issue by chteuchteu** [Templarian/MaterialDesign-Webfont#35]
[v1.8.36's meta.json](https://cdn.materialdesignicons.com/1.8.36/meta.json) file had some interesting attributes (`author`, `version`, `tags`) that are missing from [v1.9.32's meta.json](http://cdn.materialdesignicons.com/1.9.32/meta.json).

I'm using all of these (except tags for now, but I'm implementing it) in the [MaterialDesignIcons-Picker](https://github.com/chteuchteu/MaterialDesignIcons-Picker). Would it be possible to add them back?
I'd like to avoid releasing a new version without these tags

Thank you!

**Comment by Templarian** [comment]
@chteuchteu That's a bug, I accidentally used the old endpoint to build that file. The new site has updated endpoints for some of these exports. Forgot I need to use the new endpoint not the current ones to generate this file.

I'll try and look into this tonight, it definitely should be exporting all of the meta data.

After I update the file I'll purge the CDN cache so you'll see latest.

**Comment by chteuchteu** [comment]
Great, thank you!

**Comment by Templarian** [comment]
@chteuchteu I misspoke, I have to recode that change. Turns out I overwrote the changes from when my SSD died (never committed the changes into git apparently). I still should be able to recode it. 😢

**Comment by chteuchteu** [comment]
Wow, bummer :/ Good luck with that!

**Comment by Templarian** [comment]
@chteuchteu Fixed and purged the CDN cache so it's showing the latest.

Also, let me know if there is any other data you need. I'm going to be building out a UI for collaborators to tag and alias icons shortly. So hopefully shortly we'll have a solid meta.json packed with usable data. Right now it's kind of "meh" at best.

**Comment by Templarian** [comment]
oops, nvm. One sec it's not showing the right data.

**Comment by Templarian** [comment]
Now it's fixed. It was fixed before, but I exported the wrong version's meta.json. CDN is flushed and showing the correct one now.

**Comment by chteuchteu** [comment]
Awesome, thanks!
