### ISSUE TITLE
what's different in version 2?

### ISSUE THREAD

**Issue by graingert** [Templarian/MaterialDesign-Webfont#37]
Is this a breaking change?

**Comment by tagliala** [comment]
Hi,

as far as I can tell, the version number of this repository represents the number of icons in the set, so 2.0.46 = 2046 icons

**Comment by graingert** [comment]
@tagliala thanks for the advice.

@Templarian if you mark a change as breaking when it's not it messes with the ^ semver shorthand.

**Comment by Templarian** [comment]
@graingert This was _suppose_ to be a breaking change release actually dropping legacy browser support, but we're revising some of those ideas and most likely going to be including legacy support alongside modern browser support.

2.1.xx will most likely drop legacy browser support.

But yes, the icon count will always follow along with the version, not the best idea, but makes my life way easier. 😄

**Comment by graingert** [comment]
> 2.1.xx will most likely drop legacy browser support.

which browsers are considered legacy?

**Comment by graingert** [comment]
ah it's here: http://templarian.com/2017/07/24/material-design-icons-v2-0-46/#future

Surely it should be IE11+ because IE8, IE9 and IE10 all went EOL at the same time.

**Comment by Templarian** [comment]
Basically Woff / Woff2 only. Which is IE9+, along with `::before`. It's a minor change, but we're going to be providing `materialdesignicons.legacy.css` export through a flag in the scss files. This means redoing some of the build system slightly. Modern support will be the default.

Mobile side very few will notice a difference even on very old OS versions.
