### ISSUE TITLE
flag-checkered-variant is missing

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign-Webfont#38]
It's in the SVG repo, but not included in the Sass file.

**Comment by Templarian** [comment]
Please open an issue in: https://github.com/Templarian/MaterialDesign/issues

(This repo isn't followed by the contribution team)

**Comment by derwaldgeist** [comment]
Ok, thanks for the info. Why don't you just disable the issues here? ;-)

**Comment by Templarian** [comment]
I feel like it might confuse those not use to GitHub. We get a lot of 'new' devs, plus it only takes me a second to reply here. 😸

**Comment by chteuchteu** [comment]
@Templarian : what about using [issues templates](https://github.com/blog/2111-issue-and-pull-request-templates) on this repo?

> Disclaimer:
> Hi there, thanks for contributing! Before anything else, please ensure you didn't mean to create an issue on the main [MaterialDesign repo](https://github.com/Templarian/MaterialDesign/issues) instead.
> If this is intentional, just erase this message. Thanks!

**Comment by Templarian** [comment]
@chteuchteu Good idea, using your text for it.

Done. 😄
