### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Alex-Vaduva** [Templarian/MaterialDesign-Webfont#41]
Hello!

I just have a few questions regarding the license references:

1. In "package.json" and "bower.json" files besides the OFL-1.1 License, the MIT License is also mentioned. Can you please tell me on which files does the MIT apply?

2. In the "license.md" there is a Google copyright from 2014. From the link provided ( https://github.com/google/material-design-icons/blob/master/LICENSE) there were 2 versions released in 2014 with different license terms (1.0.0 -  Attribution-ShareAlike 4.0 International license and 1.0.1 - Attribution 4.0 International license). I would appreciate if you could tell me which files are from Google and which version did you use.

Thanks.

**Comment by Templarian** [comment]
Any icons marked as author `Google` are under their license. Any not are provided under the appropriate license for the file.

We are building out functionality right now in the current site to appropriately display this. It will just take some development time. This plan is to display the exact license each icon is under.

https://github.com/Templarian/MaterialDesign/issues/2705 Please use this issue to track the progress. No one on the team other than me watches this distribution repo.

http://dev.materialdesignicons.com/license (Dev server you can see a very early work in progress page).

**Comment by Alex-Vaduva** [comment]
I couldn't find any icons marked as author Google. Is there any other way to find out which icons belongs to Google?

**Comment by Templarian** [comment]
@Alex-Vaduva https://materialdesignicons.com Any icon not marked with a orange box is by Google. All orange boxed icons are from the community.
