### ISSUE TITLE
Community icons

### ISSUE THREAD

**Issue by LuSo58** [Templarian/MaterialDesign-Webfont#42]
The bower description says, that this package contains also the community created icons, but it doesn't.

EDIT: Sorry, I probably just tried one, that could have been submitted recently (folder-edit). Feel free to close the issue.

**Comment by Templarian** [comment]
Yep, that was added since the last release 8 days ago. Our next release in probably a week from now (this will be `v2.3.xx` and contain the ~50 new icons.
