### ISSUE TITLE
v2.3.54 not published on npm

### ISSUE THREAD

**Issue by aldarund** [Templarian/MaterialDesign-Webfont#43]
Latest version on npm is 2.2.43
https://www.npmjs.com/package/mdi

**Comment by Templarian** [comment]
@aldarund Thanks for reminding me I need to deprecate the `mdi` package since we moved to `@mdi/font` for all new releases of first party packages.

Will fix this later today. 😄

**Comment by Templarian** [comment]
Fixed. There is a HUGE warning on the page you listed above now about this rename.

I'll be working with the community shortly to make sure that everyone updates to the new name. Unfortunately NPM for security reasons does not allow renames.
