### ISSUE TITLE
Some icons are missing in v2.8.94

### ISSUE THREAD

**Issue by mattiagalati** [Templarian/MaterialDesign-Webfont#44]
Some icons like:
 - account-arrow-left
 - account-arrow-left-outline
 - account-arrow-right
 - account-arrow-right-outline
that are visible in website, which address version 2.8.94, are not present in same npm version.

**Comment by Templarian** [comment]
@mattiagalati All of those look to be added after `2.8.94` was released http://dev.materialdesignicons.com/history

We're wrapping up the `3.0.xx` release right now. For now just use the SVG/Vector inline.

**Comment by mattiagalati** [comment]
Many thanks.
It would be nice, if possibile, that icons not yet  packed in a release have a "new" badge, so users can be aware that the version of package does not yet include them.

**Comment by Templarian** [comment]
It's a feature that will be in the new website under development. It also lets one filter by the specific release versions. Really can't wait to get it online. 😃
