### ISSUE TITLE
Ligature support seems inconsistent

### ISSUE THREAD

**Issue by miken32** [Templarian/MaterialDesign-Webfont#45]
Tried replacing Google's WOFF and WOFF2 files with yours and started getting user reports of all the icons disappearing. I was unable to reproduce on Firefox and Chrome, but could on Safari. Other users reported problems on all browsers.

Using https://fontdrop.info/ I was unable to see ligatures (Google's font files worked fine) when typing on the "Waterfall" tab.

**Comment by Templarian** [comment]
@miken32 We don't support ligatures as we're trying to move away from the webfont (we'll always support it, but we're working on better alternatives).

https://github.com/Templarian/MaterialDesign/issues/1013

I would stick with the Google set if you need ligature support.

https://dev.materialdesignicons.com/guide/webfont-alternatives
