### ISSUE TITLE
Add font-display: swap ?

### ISSUE THREAD

**Issue by batkor** [Templarian/MaterialDesign-Webfont#47]
Hi guys! This best project.
i think, best practical if add `font-display: swap;` in `./@mdi/font/scss/_path.scss`

```
@font-face {
  ...
  ...
  font-display: swap;
}
```

Google recommended :-)
https://developers.google.com/web/updates/2016/02/font-display

**Comment by tagliala** [comment]
Hi,

we were discussing this at Font Awesome but I think that `swap` should be avoided for icon fonts.

It means that it will render a square and then the intended icon. The best option is still `block`, and it probably is the same as the default option

Ref: FortAwesome/Font-Awesome#14387

**Comment by Templarian** [comment]
Agreed, looking at the spec that looks like something we should avoid. The default behavior (`auto`/`block`) is what we would want in this case, so leaving it off should be fine.

Wish there was a option that sets it a high priority for fonts that use private characters where there isn't a reasonable fallback.

**Comment by batkor** [comment]
Thank, Ok
