### ISSUE TITLE
Icons missing : pdf-box and file-pdf-outline

### ISSUE THREAD

**Issue by fschlaef** [Templarian/MaterialDesign-Webfont#48]
The demo on https://materialdesignicons.com/ (supposedly in 3.5.95) lists `pdf-box` and `file-pdf-outline` as available. However, neither are to be found in  https://github.com/Templarian/MaterialDesign-Webfont/blob/v3.5.95/css/materialdesignicons.css

`pdf-box` was apparently added in February according to https://github.com/Templarian/MaterialDesign/issues/1339 but it is unclear if it was for 3.5.xx or 3.6.xx

Thank you for clarifying this.

**Comment by Templarian** [comment]
Was out of town on vacation, so a bit slow on replying. Doing the release for 3.6.95 right now. This includes these. The website itself shows WIP icons as most viewing that page are using the site's download feature.

Reference the history page is the easiest way to see what is in the next release. https://dev.materialdesignicons.com/history

[CDN v3.5.95](https://cdn.materialdesignicons.com/3.5.95/) vs [CDN v3.6.95](https://cdn.materialdesignicons.com/3.6.95/)

**Comment by fschlaef** [comment]
@Templarian thank you very much for the clarification.

May I suggest identifying WIP icons on website ? (with a border maybe, like community icons) 
Could avoid this kind of confusion in the future, although I don't know how often is happens.
