### ISSUE TITLE
Drop eot, svg, ttf and woff support?

### ISSUE THREAD

**Issue by francoism90** [Templarian/MaterialDesign-Webfont#50]
woff2 should be supported by most devices/browsers. It would be an idea to move them to a separate package instead, although removing support would be a better option:
```
fonts/vendor/@mdi/materialdesignicons-webfont.eot?be7691c114e7c9d0543b89e824c4003d   534 KiB          [emitted]  [big]  
fonts/vendor/@mdi/materialdesignicons-webfont.svg?c68a0a65b3a0be718f4c81c02c5f69ca     4 MiB          [emitted]  [big]  
fonts/vendor/@mdi/materialdesignicons-webfont.ttf?6acc7d6cffa21f6eda4baaa90e835fd2   534 KiB          [emitted]  [big]  
fonts/vendor/@mdi/materialdesignicons-webfont.woff2?84c6fe1e4353c916d8f1452e82bdef8d   189 KiB          [emitted]         
fonts/vendor/@mdi/materialdesignicons-webfont.woff?1a95531b09ffc9b76104e0003b456a0e   257 KiB          [emitted]  [big]
```
 
If this should be in the main repo, please let me know. :)

**Comment by Templarian** [comment]
There is a plans to remove SVG in the next `3.7.xx` release! We will leave the others for now.

https://github.com/Templarian/MaterialDesign/issues/4166

Can you create an issue with data backing up us removing the others (won't happen in the 3.7.xx release, but we can consider it for 4.0 as it is a larger impact). Right now nothing uses SVG.

Thanks!

**Comment by Templarian** [comment]
@francoism90 Yes in the main repo. I'm the only one that monitors this repo, so the core team will not see it here.

**Comment by PeterShaggyNoble** [comment]
Full browser support details for WOFF2 here: https://caniuse.com/#feat=woff2

And, for reference:
- EOT: https://caniuse.com/#feat=eot
- TTF: https://caniuse.com/#feat=ttf
- WOFF: https://caniuse.com/#feat=woff
