### ISSUE TITLE
Error with version 3.7.94

### ISSUE THREAD

**Issue by jahirfiquitiva** [Templarian/MaterialDesign-Webfont#52]
Hello, I'm getting this error with webpack after last update

```bash
ModuleNotFoundError: Module not found: Error: Can't resolve '../fonts/materialdesignicons-webfont.svg?v=3.7.94' in '/app/node_modules/@mdi/font/css'
```

**Comment by Templarian** [comment]
Unpublished. Releasing `3.7.95` in a minute. Oversight in the build script when removing the SVG font files.

**Comment by Templarian** [comment]
@jahirfiquitiva https://cdn.materialdesignicons.com/3.7.95/ Fixed?

**Comment by jahirfiquitiva** [comment]
yep ... fixed now... thanks
