### ISSUE TITLE
[BUG] Inconsistency on css naming

### ISSUE THREAD

**Issue by Sebastian-G** [Templarian/MaterialDesign-Webfont#53]
On https://materialdesignicons.com/icon/weather-partly-cloudy declared as "weather-partly-cloudy"

But on scss declaration _variables.scss @ line:3689
```
...
"weather-partlycloudy": F595,
...
```

The "-" is missing on SCSS class mapping.

**Comment by Sebastian-G** [comment]
https://github.com/Templarian/MaterialDesign-Webfont/blob/67cb28c882b7099f0d46b2a63a442d5fa0c43249/scss/_variables.scss#L3689

**Comment by Sebastian-G** [comment]
and https://materialdesignicons.com/icon/weather-partly-rainy is missing @ all

**Comment by Templarian** [comment]
This is a rename going into the next release. We're adding a lot of new weather icons. Ironically that will be the only rename.

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/history
