### ISSUE TITLE
Confusing versioning

### ISSUE THREAD

**Issue by Shinigami92** [Templarian/MaterialDesign-Webfont#54]
# Confusing versioning

Unfortunately I cant see through the versioning any more.

![Bildschirmfoto 2019-08-14 um 16 12 24](https://user-images.githubusercontent.com/7195563/63028086-69cadc00-beae-11e9-9e8a-ba3672235530.png)

- What changes have been made between version 3.x and 4.x?
- Is there a `changelog.md`?
- Are there any breaking changes from 3 to 4?

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/changelog
https://dev.materialdesignicons.com/upgrade

There were 5 icon renames. I haven't had a second to update the changelog/upgrade guide. Got busy at the office this morning.

https://github.com/Templarian/MaterialDesign-SVG/commit/cfdc4ff2b4e4ae08f94b7a349c5f0c197ae034b7 You can see the changes here for now.

**Comment by Templarian** [comment]
Use fixed versioning when using any of the NPM packages. We recommend only upgrading when you need new icons.

**Comment by Shinigami92** [comment]
Ah thank you -> https://dev.materialdesignicons.com/changelog

Maybe we can create a CHANGELOG.md in this repo and provide this url
Or we provide this two links in the README.md

So when we upgrade our package.json, we can find it more quickly

**Comment by Templarian** [comment]
Was trying not to link to the dev box. Let me wire up some redirects for now and get it linked in the readme of each. The next release is going out this weekend (we have the next 3 releases finalized already).

Eventually the tooling will generate this file automatically. I already have the info needed, just need to wire everything up.

**Comment by Templarian** [comment]
Closing this out as 5+ versioning follows a semver'ish breaking change only with major releases.
