### ISSUE TITLE
SVG Font

### ISSUE THREAD

**Issue by vitorhugojapa** [Templarian/MaterialDesign-Webfont#55]
Hi! I've seen on Issue #4166 that the SVG Font has been removed from the project.
That font was **REALLY** helpful to us in our workflow.

We used it on Sketch along with the "Sketch Icon" plugin.
There we could import a custom SVG font and use all of the icons directly on the Sketch File, using the plugin to find the desired icon.

Last week we wanted to update to the latest version but it was not possible since the SVG font is not available anymore.

**Comment by Templarian** [comment]
Closing this out as I think this should be fine for now. We'll work on adding additional download options later.

https://github.com/Templarian/MaterialDesign-Site/issues/113

@vitorhugojapa If you can link to the sketch plugin name and let us know what's required we'll add a page dedicated for Sketch users. 😃
