### ISSUE TITLE
Source map `sources` is wrong

### ISSUE THREAD

**Issue by iBelieve** [Templarian/MaterialDesign-Webfont#57]
Both [source maps](https://github.com/Templarian/MaterialDesign-Webfont/blob/master/css/materialdesignicons.css.map) (minified and non-minified) refer to the scss sources as `dist/scss/*`. This isn't correct, as there's no dist folder. I was previously using [v3.7.95](https://github.com/Templarian/MaterialDesign-Webfont/blob/v3.7.95/css/materialdesignicons.css.map), which worked correctly and used `../scss/*` as the sources path in the source maps.

**Comment by Templarian** [comment]
@iBelieve Really good catch! We completely replaced our build system with a new code stack in that release onward (as it was 5 years old).

Will get a fix in for the next release of `@mdi/font` and `@mdi/font-build`.

Thank you for opening this issue, surprised no noticed.

**Comment by Templarian** [comment]
@iBelieve https://cdn.materialdesignicons.com/4.5.95/ This will be going out this week.

**Comment by Templarian** [comment]
Forgot to close this the other day. 😃

**Comment by iBelieve** [comment]
Thanks for the fix!
