### ISSUE TITLE
Remove unnecessary whitespace on `<i>` element

### ISSUE THREAD

**Issue by marcost5m** [Templarian/MaterialDesign-Webfont#58]
Started using this collection and I've noticed that all the `<i>` elements for each icon have some type of extra whitespace, more noticeable on top/bottom, but the `::before` itself has the correct height of the icon. I haven't found a way of removing this with CSS.

**Comment by Templarian** [comment]
@marcost5m Can you please create a codepen or jsbin example showing this? Need some more details on reproducing this. Please make sure you're using the latest version also.

**Comment by Templarian** [comment]
Closing this out as I haven't heard anything back on reproducing this issue.
