### ISSUE TITLE
Preloading the font request

### ISSUE THREAD

**Issue by iamntg** [Templarian/MaterialDesign-Webfont#61]
Hi there,

I am wondering if we could load the file from local first in order to improve the preloading.

in the @ font-face

@ font-face {
  font-family: "Material Design Icons";
  src: **local("Material Design Icons")** url("../fonts/materialdesignicons-webfont.eot?v=4.8.95");
  src: **local("Material Design Icons")** url("../fonts/materialdesignicons-webfont.eot?#iefix&v=4.8.95") format("embedded-opentype"), url("../fonts/materialdesignicons-webfont.woff2?v=4.8.95") format("woff2"), url("../fonts/materialdesignicons-webfont.woff?v=4.8.95") format("woff"), url("../fonts/materialdesignicons-webfont.ttf?v=4.8.95") format("truetype");
  font-weight: normal;
  font-style: normal;
}

like this?

This is recommended as the PWA performance improvements

**Comment by Templarian** [comment]
We do not advise people to install this font locally. Eventually we are going to work on making a font that is more deal for local usage. Until then we advise using the SVG files in design software.
