### ISSUE TITLE
"cog" icon with wrong name

### ISSUE THREAD

**Issue by pdcmoreira** [Templarian/MaterialDesign-Webfont#63]
The ["cog" icons](https://materialdesignicons.com/icon/cog) and its variants are named "settings" in this package.
https://github.com/Templarian/MaterialDesign-Webfont/blob/c8ed1f706deb089e05cb46655a786210991f1e92/css/materialdesignicons.css#L16113-L16135

Took me a while to understand why my `mdi-cog` icon was not showing up.

**Comment by Templarian** [comment]
@pdcmoreira Sorry about that, you need to use the CDN preview to see the correct names.

We're preparing for the 5.0 release which includes several breaking changes. One breaking change just happens to be our renaming of `-settings` to the `noun` representation `cog`. One bonus of this is we're adding the `-cog` overlay to many more icons.

https://cdn.materialdesignicons.com/4.9.95/

5.0 is our large push to fix icon names that were incorrect or confusing, so we can prepare for the next 5000 icons.

> Future issues can be opened in the main repo, this is a distribution repo.

**Comment by Templarian** [comment]
More info: https://github.com/Templarian/MaterialDesign/issues/4806
