### ISSUE TITLE
Missing Icons in webfont css

### ISSUE THREAD

**Issue by MatthewAry** [Templarian/MaterialDesign-Webfont#64]
**mdi-sort-alphabetical-ascending** which should resolve to [this icon](https://dev.materialdesignicons.com/icon/sort-alphabetical-ascending)
resolves to [this icon](https://dev.materialdesignicons.com/icon/sort-alphabetical-ascending-variant). This can be seen when using appropriate css class to try to resolve for the icon.

Other sort related icons are also missing including but not limited to:

- sort-bool-ascending
- sort-bool-descending
- sort-bool-ascending-variant
- sort-bool-descending-variant
- sort-alphabetical-ascending-variant
- sort-alphabetical-descending-variant

**Comment by Templarian** [comment]
These are all part of the 5.0 release and are not currently released. Probably 2 weeks until these ones go out.
