### ISSUE TITLE
mdi-account-alert-outline class not working

### ISSUE THREAD

**Issue by nacee-hu** [Templarian/MaterialDesign-Webfont#66]
A blank icon appears...

.mdi-account-alert-outline::before {
    content: "\FB2C";
}

**Comment by puyt** [comment]
I just noticed it's only blank when I use it with a font-size of 16px, when I increase or decrease the font-size it magically appears

**Comment by nacee-hu** [comment]
This is Interesting and true, though in my case it is blank at 32px, but if I change size, it really shows.

**Comment by Templarian** [comment]
@nacee-hu / @puyt Can I get some details about browsers/OS you're using? I tried on my Windows in Chrome and Mac (not updated to Catalina yet) in Chrome.

https://cdn.materialdesignicons.com/5.0.45/

Even though we just did the large 5.0 release we almost have 5.1.x finalized and I would like to make sure this isn't an issue before it's released.

**Comment by nacee-hu** [comment]
I use 4.9.95 version, and I tested on Ubuntu OS, Chrome browser...

**Comment by Templarian** [comment]
Okay, going to assume both are on Linux and something is incompatible. Once I find it I'll script up a way to scan all 5k icons for the issue. 🤔

Definitely not something I've seen before. Can you verify it is happening in 5.0.45?

**Comment by nacee-hu** [comment]
5.0.45 working fine

**Comment by nacee-hu** [comment]
I think this issue can be closed.
When will version 5.1.x be released?

**Comment by Templarian** [comment]
Probably 2 weeks, unless we need to publish to fix a regression. Thanks for testing with v5 as it includes updates to our build tooling that probably fixed this.
