### ISSUE TITLE
Missing icons from 5.0.45 release

### ISSUE THREAD

**Issue by ThomasKientz** [Templarian/MaterialDesign-Webfont#67]
The 5.0.45 release of css fonts is missing icons like : `flask-off` or `mushroom-off`  of the latest release.

**Comment by Templarian** [comment]
Those are not released. Those are part of the v5.1.45 which will release in about 2 weeks.

https://dev.materialdesignicons.com/history

We're working on a new site that will make it more obvious if an icon is not in a release.

**Comment by Templarian** [comment]
@ThomasKientz 5.1.45 released a few hours ago. Will be announced tomorrow. Just a heads up.
