### ISSUE TITLE
Icon renames

### ISSUE THREAD

**Issue by juhasev** [Templarian/MaterialDesign-Webfont#68]
Why do the icon names keep changing between versions? We just upgraded and a lot of icons are now missing. We have literally hundreds of these to update....

**Comment by Templarian** [comment]
v5.0 was a major update: https://github.com/Templarian/MaterialDesign/issues/4901

https://dev.materialdesignicons.com/upgrade

Long story is that we are no longer maintaining brand icons and are working with Simple Icons to fill the void as they do a much better job keeping their brand icons up to date.

After 5.0 it will be a lot smoother. After almost 7 years we had to finally go back and fix the project as it has grown a lot in that time. It is annoying, but it will make the next 5000 icons a lot smoother.

**Comment by Templarian** [comment]
5.1.45 actually just released 3 hours ago (haven't announced it yet, so update to that if you can).

**Comment by juhasev** [comment]
Ok. I will try that out. I was looking at the release notes before upgrading but there is no info about the renames. I would be nice to include the link to upgrades so you can do better audit before each upgrade. It seems like it was not too bad after all, thats to today's wonderful IDEs.
