### ISSUE TITLE
MDI Variable $sizes is conflicting with bootstrap

### ISSUE THREAD

**Issue by npoggenburg** [Templarian/MaterialDesign-Webfont#70]
Hi,

the variable $sizes you are using in this packages is conflicting with bootststrap:
// This variable affects the `.h-*` and `.w-*` classes.
$sizes: () !default;
// stylelint-disable-next-line scss/dollar-variable-default
$sizes: map-merge(
  (
    25: 25%,
    50: 50%,
    75: 75%,
    100: 100%,
    auto: auto
  ),
  $sizes
);

used in:
node_modules/bootstrap/scss/utilities/_sizing.scss

For best practice, the scss vars should be prefixed with mdi- so your variables are like $mdi-sizes to prevent any conflicts with other code.

Best regards,
Nico

**Comment by Templarian** [comment]
@npoggenburg There are no variables called `$sizes`. That was patched back in Feb 19, 2018.

https://github.com/Templarian/MaterialDesign-Webfont/commit/31ea782ab75a528350d6a350a722ddade6d16596#diff-dde4a3ede9ecb8fd275ea5a53cbf52d2
