### ISSUE TITLE
Missing cash-check icon

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [Templarian/MaterialDesign-Webfont#71]
It's in the main repo but with `@mdi/font` it doesn't work, might be also problem with other cash-* icons:

https://codepen.io/jkarczm/pen/abdYjLY?editors=1000

**Comment by Templarian** [comment]
@jacekkarczmarczyk We did two large releases back to back and are taking a break to focus on the website. I'll probably cut a release at 50 icons. Until then try and use an inline SVG or alternative icon.
