### ISSUE TITLE
None of the "face man" icons work.

### ISSUE THREAD

**Issue by nekooee** [Templarian/MaterialDesign-Webfont#75]
None of the "face man" icons work. 
![image](https://user-images.githubusercontent.com/6003803/109386891-1e064900-7913-11eb-8759-ddeb6d935a0a.png)

**Comment by Templarian** [comment]
@nekooee We're updating the naming for 6.0 unfortunately the current site doesn't let us version the name changes.

https://pictogrammers.github.io/@mdi/font/5.9.55/ You can use the CDN preview to see a specific release.

- History Page: https://dev.materialdesignicons.com/history
- v6.0 work: https://github.com/Templarian/MaterialDesign/issues/5409
