### ISSUE TITLE
Issues with glyph names: wrong names in cheatsheet, duplicate glyph names, zero-length names

### ISSUE THREAD

**Issue by callegar** [Templarian/MaterialDesign-Webfont#78]
Hi, I am trying to use the MaterialDesign-Webfont with LuaLaTeX a typesetting program able to deal with ttf and otf fonts (differently from other versions of LaTeX).

The problems that I am encountering are the following:

- glyph names do not appear to be imported. If I understand it correctly, it happens because some glyph have names with zero length. It is not completely clear to me whether this is a real issue or more of a limitation in LuaLaTeX.  In any case, I wonder, if this project could make a step in helping the icon usage with LuaLaTex; clearly it is much nicer to be able to instantiate an icon by name than by codepoint.

- the cheatsheet does not seem to fully correspond to the font. For instance, it has been checked that:
> “music-note” appears twice in the font encoding, at F0387 and F0388. The cheat sheet says that the second of those should be “music-note-eight”; “checkbox-blank-circle-outline”, is at F0766 and F043D. The latter should have been named “radiobox-blank” according to the cheat sheet.

- the duplicate names mentioned at the previous point are extra problematic for LuaLaTeX. In fact, because of how it is designed, LuaLaTeX needs to use parts of the PUAs for remapping glyphs of its own (for rather complex reasons that would be out of scope here). As a consequence, to the best of my understanding it is a bit aggressive in managing the PUAs. Items that appear as duplicate get discarded with the result that any glyph appearing right after will get an offset in the codepoint.

For a thorough discussion of the matter, please see the ConTeX mailing list thread at https://mailman.ntg.nl/pipermail/ntg-context/2021/102074.html . It is ConTeXt, not LuaLaTeX, but it does not matter as they share the font management code, that in fact originates from ConTeXt (and that's why the discussion is there).

Would really be good if this great project could actually help using its icons also out of the web! Thanks in advance if there is something that can be done.

**Comment by Templarian** [comment]
Please use the desktop font: https://github.com/Templarian/MaterialDesign-Font

(I don't really monitor this repo unfortunately as it's only for distribution of the webfont)
