### ISSUE TITLE
Ask list icon page

### ISSUE THREAD

**Issue by Dhanamerdeka** [Templarian/MaterialDesign-Webfont#79]
hello.
on past i using https://cdn.materialdesignicons.com/5.0.45/ to see the list of icon etc... and now it's redirected to https://cdn.jsdelivr.net/npm/@mdi/font@5.0.45/

can you know where old page that have list icon located?
something like 
![image](https://user-images.githubusercontent.com/29838157/123760314-eae8bc00-d8ea-11eb-8218-7e47c138ab2a.png)

**Comment by Dhanamerdeka** [comment]
i mean page like this....
![image](https://user-images.githubusercontent.com/29838157/123762683-3d2adc80-d8ed-11eb-8ccc-3164fc7baa3a.png)
can you make it appear again? instead this
![image](https://user-images.githubusercontent.com/29838157/123762745-4caa2580-d8ed-11eb-8b6b-3d8cb7e4f992.png)
because for me... i need that's things to choose, copy and use the code to call the icon

**Comment by Templarian** [comment]
https://pictogrammers.github.io/@mdi/font/6.1.95/

We switched CDN partners. The do not allow serving static `index.html`, so we moved them over to our org's github pages.

I'll make sure I didn't leave any legacy links in the docs/site.
