### ISSUE TITLE
Rounding issues?

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign-Webfont#8]
Simplistic icons, which are mostly "on pixel", do not require many decimal places for path points. Thus, SVGs can be optimized a lot (up to 3 decimal places for fine details, and none for on-pixel points).

If I look at the resulting SVG font here however, there are a lot of values with 13 (!) decimal places. Doesn't seem right to me.

**Comment by Templarian** [comment]
I don't use the SVG files here, those are all the raw SVG data. I run multiple optimization scripts on the SVG path data (and a few custom ones that do some more advanced curve related optimizations).

To see the path data you can view it on the https://materialdesignicons.com/custom page. Press the download custom.txt.
