### ISSUE TITLE
icons appear as hollow boxes when compiling angular project with production flag

### ISSUE THREAD

**Issue by kfirufk** [Templarian/MaterialDesign-Webfont#80]
Hello.

I use angular 12.1.1 but I had this problem since older versions as well. I added @mdi/font package to my project, when I build my project for productions with `ng build --configuration production`, with older versions it was `ng build --prod`, I noticed that instead of the icons i see hollow boxes instead. 

any ideas why?

**Comment by Templarian** [comment]
Probably a path issue or it's not picking up the assets?

Closing this out as we don't recommend the webfont for Angular applications. https://dev.materialdesignicons.com/getting-started/angular
