### ISSUE TITLE
Missing icons in v5.9.55

### ISSUE THREAD

**Issue by nextage** [Templarian/MaterialDesign-Webfont#81]
Release v5.9.55 has some missing icons.
e.g. sticker-text, sticker-text-outline, arrow-up-right, etc

**Comment by JoshMayberry** [comment]
Another one that is missing is archive-settings.

The desktop font gets updated every time a new icon is added.
When does the webfont get updated? It looks like it hasn't updated in 7 months (at the time of writing this).

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign/issues/5409

**Comment by vraravam** [comment]
The `mdi-settings` icon shows up with zero height. Is this something that should be tracked within this bug? Or in Templarian/MaterialDesign#5409 ?
