### ISSUE TITLE
BUG: Vite build Error

### ISSUE THREAD

**Issue by marsanla** [Templarian/MaterialDesign-Webfont#85]
Hi I am getting this issues when I want to build a vue with vite:

`[vite:resolve] Failed to resolve entry for package "@mdi/font". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@mdi/font". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "@mdi/font". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@mdi/font". The package may have incorrect main/module/exports specified in its package.json.`

**Comment by Templarian** [comment]
Probably wanted the `@mdi/js` package and not the the webfont. No one should be using the webfont in modern development as it includes all of the icons.
