### ISSUE TITLE
Missing icon (image-plus-outline)

### ISSUE THREAD

**Issue by MasterPG5** [Templarian/MaterialDesign-Webfont#86]
Hi!
I'd like to report that I found an icon (and probably more) that are missing from the fonts, however they were added to the main repo 2 weeks ago. Can you please update the fonts, so that I can use that icon?
Here you can find it:
https://github.com/Templarian/MaterialDesign/issues/6612

**Comment by Templarian** [comment]
We don't really monitor the distribution repos.

`7.0.96` is out now.
