### ISSUE TITLE
Printer icons missing in font files

### ISSUE THREAD

**Issue by gabrielrbarbosa** [Templarian/MaterialDesign-Webfont#88]
According to https://materialdesignicons.com/, the mdi-printer-pos-* icons are available in the current version (I'm using 7.0.96). When checking the materialdesignicons.css file, it is missing though. I could only find 'mdi-printer-pos', as shown in the search below.

![Capturar3](https://user-images.githubusercontent.com/12158575/190257414-dc09f6ba-94bb-43d6-90b8-b3c2bd25d05f.PNG)

**Comment by Templarian** [comment]
Those are in the 7.1.xx release that hasn't gone out yet. You can view the 7.1.xx milestone in the main repo (this repo is really only for distribution).

https://github.com/Templarian/MaterialDesign/milestone/65?closed=1
